version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            sudo pip install pytest
            pytest --rootdir=~/repo
